Feature/intellij login
watermelontools/watermelon pull request #286
Opened 2023-09-06 19:48 UTC by EstebanDalelR

## Description
This will allow the user to login in IntelliJ
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Notes

## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

2023-09-07 15:05 UTC, baristaGeek commented
Can you please provide testing instructions?

2023-09-11 15:53 UTC, baristaGeek requested changes

2023-09-11 15:53 UTC, baristaGeek commented on app/api/extension/intellijLogin/route.ts
> +  const userData = await intellijLogin({ watermelon_user: token });
If a watermelon_user is invalid, the request that returns` {"data": [ ]}` shouldn't return 200.

2023-09-11 16:12 UTC, EstebanDalelR commented
> Can you please provide testing instructions?

Use postman to send an email as "token"

2023-09-13 15:31 UTC, baristaGeek approved these changes

2023-09-13 15:34 UTC, merged