Test using the installation id
watermelontools/watermelon pull request #326
Opened 2023-10-12 23:23 UTC by EstebanDalelR

## Description
Uses the app token instead of the user token to get info
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)  
- [x] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update  
- [ ] Chore: cleanup/renaming, etc  
- [ ] RFC  
## Notes

## Acceptance

- [x] I have read [the Contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)

2023-10-13 16:10 UTC, baristaGeek commented on utils/actions/getAllServices.ts
> +  const [github, teamGitHub, jira, confluence, slack, notion, linear, asana] =
Nice idiomatic var name

2023-10-13 16:20 UTC, baristaGeek reviewed
Testing notes:

- Tested with the previously successful payload on #324 and it works 
- Tested on #328 after deleting estebanvargas94 (username associated to the estebanvargasgarcia1994@gmail.com email) with the previously successful payload that I used to create the PR. Got a new comment asking me to login 
<img width="740" alt="Screen Shot 2023-10-13 at 12 22 43 PM" src="https://github.com/watermelontools/watermelon/assets/8325094/e17e3d89-6772-4878-841e-50125a48ceaa">

2023-10-17 20:30 UTC, EstebanDalelR commented on app/api/actions/github/route.ts
> +                body: "[Please login to GitHub in Watermelon to see the results](https://app.watermelontools.com/)",
Fix to the text, there is no way to find a user without them logging in.
@baristaGeek

2023-10-18 20:33 UTC, baristaGeek approved these changes
Approving understanding the technical restrictions that we have.

2023-10-24 17:20 UTC, baristaGeek requested changes
We must handle this case. I used my estebanvargasgarcia1994@gmail.com account. 

<img width="1188" alt="Screen Shot 2023-10-24 at 12 09 55 PM" src="https://github.com/watermelontools/watermelon/assets/8325094/8ddf3445-d46c-4d1a-8942-057b712ef2f2">

2023-10-24 17:53 UTC, baristaGeek requested changes
Ran with baristaGeek (estebanvargas94@gmail.com) which is part of the team and the team's query count didn't increase

https://github.com/watermelontools/watermelon/assets/8325094/bd93818a-b267-4f8f-bf42-c6b33288988e

2023-10-24 18:32 UTC, baristaGeek requested changes
This user flow should behave as follows:
1. Opening a PR with estebanvargasgarcia1994@gmail.com (a user not part of the dbo.github table but part of the team)
2. On the remote branch (feature/team-GH-fetch)
3. PR is contextualized and pre-reviewed

https://github.com/watermelontools/watermelon/assets/8325094/226aac6a-6ba4-4cfc-88a2-c3677e15db7e

2023-10-25 22:37 UTC, baristaGeek commented
> We must handle this case. I used my [estebanvargasgarcia1994@gmail.com](mailto:estebanvargasgarcia1994@gmail.com) account.
> 
> <img alt="Screen Shot 2023-10-24 at 12 09 55 PM" width="1188" src="https://user-images.githubusercontent.com/8325094/277750009-8ddf3445-d46c-4d1a-8942-057b712ef2f2.png">

This is working properly now

2023-10-25 22:37 UTC, baristaGeek commented
> Ran with baristaGeek ([estebanvargas94@gmail.com](mailto:estebanvargas94@gmail.com)) which is part of the team and the team's query count didn't increase
> 
>  Screen.Recording.2023-10-24.at.12.51.45.PM.mov

If this improves cool, but it's not a priority

2023-10-25 22:44 UTC, baristaGeek commented
I think we're very close! I didn't get "user not registered" as the last time and actually got a successful response. 

Is the only thing left to do actually executing the commenting -> detecting console logs -> labeling the PR flow? 

<img width="711" alt="Screen Shot 2023-10-25 at 5 23 54 PM" src="https://github.com/watermelontools/watermelon/assets/8325094/0410ccf5-7e50-4802-b991-04f90b70f4fa">

2023-10-26 18:05 UTC, baristaGeek approved these changes
Approving because it's working better than the current version of #334 (I recognize there are merge conflicts). The hard part works :tada: :tada:

We just have to fix `placeholder={`Teammate@${teamName.toLowerCase()}.com`}` which is something minor

2023-10-26 19:19 UTC, EstebanDalelR commented
> We just have to fix `placeholder={`Teammate@${teamName.toLowerCase()}.com`}` which is something minor

Weird, this line hasn't ever been touched.

2023-10-26 19:29 UTC, EstebanDalelR commented
Anyway I opened #342 with that.

2023-10-26 21:38 UTC, baristaGeek commented
> > We just have to fix `placeholder={`Teammate@${teamName.toLowerCase()}.com`}` which is something minor
> 
> Weird, this line hasn't ever been touched.

You're right this is broken in prod. Let's fix it. For now let's merge this

2023-10-26 22:36 UTC, merged